# Generated by Django 5.1.5 on 2025-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Finanças', 'Financeiro'), ('Atendimento', 'Atendimento'), ('Orçamento', 'Orçamento'), ('TI', 'TI')], max_length=30),
        ),
    ]
